In [8]:
from google.colab import files
files.upload()

Saving Loan-Approval-Prediction (1).csv to Loan-Approval-Prediction (1) (2).csv


{'Loan-Approval-Prediction (1) (2).csv': b'Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status\r\nLP001002,Male,No,0,Graduate,No,5849,0,,360,1,Urban,Y\r\nLP001003,Male,Yes,1,Graduate,No,4583,1508,128,360,1,Rural,N\r\nLP001005,Male,Yes,0,Graduate,Yes,3000,0,66,360,1,Urban,Y\r\nLP001006,Male,Yes,0,Not Graduate,No,2583,2358,120,360,1,Urban,Y\r\nLP001008,Male,No,0,Graduate,No,6000,0,141,360,1,Urban,Y\r\nLP001011,Male,Yes,2,Graduate,Yes,5417,4196,267,360,1,Urban,Y\r\nLP001013,Male,Yes,0,Not Graduate,No,2333,1516,95,360,1,Urban,Y\r\nLP001014,Male,Yes,3+,Graduate,No,3036,2504,158,360,0,Semiurban,N\r\nLP001018,Male,Yes,2,Graduate,No,4006,1526,168,360,1,Urban,Y\r\nLP001020,Male,Yes,1,Graduate,No,12841,10968,349,360,1,Semiurban,N\r\nLP001024,Male,Yes,2,Graduate,No,3200,700,70,360,1,Urban,Y\r\nLP001027,Male,Yes,2,Graduate,,2500,1840,109,360,1,Urban,Y\r\nLP001028,Male,Yes,2,Graduate,No,3073

In [57]:

import pandas as pd
df = pd.read_csv("Loan-Approval-Prediction (1).csv")

In [58]:
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [34]:
df.describe()


ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [80]:
df.columns

Index(['Dependents', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Loan_Status'],
      dtype='object')

In [81]:
df = df.drop(["Dependents"], axis=1)



In [83]:
df.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         0.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Loan_Status  
0             1.0           1  
1             1.0           0  
2             1.0           1  
3             1.0           1  
4             1.0           1

In [84]:
df.columns

Index(['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Loan_Status'],
      dtype='object')

In [85]:
features = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History']

In [86]:
df.loc[df["Loan_Status"] == "Y", "Loan_Status"] = 1
df.loc[df["Loan_Status"] == "N", "Loan_Status"] = 0

In [87]:
import numpy as np
df['LoanAmount'] = df['LoanAmount'].replace(np.nan, 0)
df.head()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         0.0             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Loan_Status  
0             1.0           1  
1             1.0           0  
2             1.0           1  
3             1.0           1  
4             1.0           1

In [88]:
y = df['Loan_Status']
X = df[features]
y = y.astype('int')

In [72]:
df.head()

Dependents  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0          0             5849                0.0         0.0   
1          1             4583             1508.0       128.0   
2          0             3000                0.0        66.0   
3          0             2583             2358.0       120.0   
4          0             6000                0.0       141.0   

   Loan_Amount_Term  Credit_History Loan_Status  
0             360.0             1.0           1  
1             360.0             1.0           0  
2             360.0             1.0           1  
3             360.0             1.0           1  
4             360.0             1.0           1

In [110]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import fbeta_score, make_scorer, accuracy_score, precision_score, recall_score


In [111]:
# Initialize the base model (Decision Tree)
base_model = DecisionTreeClassifier(random_state=42)

In [116]:
bagging_classifier = BaggingClassifier(n_estimators=5,random_state=0)

In [118]:
scores = cross_val_score(bagging_classifier, X, y, cv=5, scoring='precision', error_score='raise')
print(scores)
print(scores.mean())

[0.82222222 0.74193548 0.78350515 0.86075949 0.79775281]
0.801235032678403


In [121]:
scores = cross_val_score(bagging_classifier, X, y, cv=5, scoring='recall', error_score='raise')
print(scores)
print(scores.mean())

[0.87058824 0.81176471 0.9047619  0.80952381 0.8452381 ]
0.848375350140056


In [122]:
scores = cross_val_score(bagging_classifier, X, y, cv=5, scoring='accuracy', error_score='raise')
print(scores)
print(scores.mean())

[0.7804878  0.67479675 0.76422764 0.7804878  0.74590164]
0.7491803278688525


In [123]:
f2_scorer = make_scorer(fbeta_score, beta=2)
scores = cross_val_score(bagging_classifier, X, y, cv=5, scoring=f2_scorer, error_score='raise')
print(scores)
print(scores.mean())

[0.86046512 0.79676674 0.87759815 0.81927711 0.83529412]
0.8378802476867533


In [ ]:
scores = cross_val_score(bagging_classifier, X, y, cv=5, scoring='recall', error_score='raise')
print(scores)
print(scores.mean())

In [96]:
from sklearn.ensemble import RandomForestClassifier
random_forest_classifier = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=0)

In [97]:
print(X.dtypes)

ApplicantIncome        int64
CoapplicantIncome    float64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
dtype: object


In [99]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import fbeta_score, make_scorer
from sklearn import metrics
scores = cross_val_score(random_forest_classifier, X, y, cv=5, scoring='precision', error_score='raise')
print(scores)
print(scores.mean())

[0.79207921 0.76415094 0.77358491 0.83333333 0.80808081]
0.7942458396783075


In [100]:
scores = cross_val_score(random_forest_classifier, X, y, cv=5, scoring='recall', error_score='raise')
print(scores)
print(scores.mean())

[0.94117647 0.95294118 0.97619048 0.95238095 0.95238095]
0.9550140056022409


In [101]:
scores = cross_val_score(random_forest_classifier, X, y, cv=5, scoring='accuracy', error_score='raise')
print(scores)
print(scores.mean())

[0.78861789 0.76422764 0.78861789 0.83739837 0.81147541]
0.7980674396907903


In [109]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import fbeta_score, make_scorer
f2_scorer = make_scorer(fbeta_score, beta=2)
scores = cross_val_score(random_forest_classifier, X, y, cv=5, scoring=f2_scorer, error_score='raise')
print(scores)
print(scores.mean())

[0.90702948 0.90807175 0.92760181 0.92592593 0.91954023]
0.9176338386205417
